### PR TITLE
Prestrafe comparison

### PR DESCRIPTION
**Pull request by Topvennie**
New feature which shows the difference between your prestrafe speed and the map record.

On a linear map or the first stage of a staged map it compares with the prestrafe speed of the map record.
For the other stages it compares with the stage record.
Bonus prestrafes are compared bonus records.

### CODE REVIEW

**Review by dPexxIAM — APPROVED** [review]
LGTM! Thanks for this!!

**Comment by Bara** [comment]
And from where do we get the "ghost tables"? :)

**Comment by dPexxIAM** [comment]
As bara said, this will require an update script for the DB schema before we can push a new release with these changes.

**Comment by Topvennie** [comment]
Not sure what you mean with ghost tables
But if you mean the prestrafe data itself then if there's no saved data aka the prestrafe speed = 0 then it doesn't show the difference and just prints "start prestrafe: 340 u/s"

It also starts saving the prestrafe data.

Worked for me with the current Db schema

**Comment by Bara** [comment]
@Topvennie you seems to use the OldDev branch or another fork with the db changes. Offical the ck_bonus has the following columns: steamid, name, mapname, runtime, zonegroup and style

**Comment by Bara** [comment]
You could look into the "CREATE TABLE" queries >[here](https://github.com/surftimer/Surftimer-Official/blob/master/addons/sourcemod/scripting/surftimer/db/queries.sp)<.

**Comment by Topvennie** [comment]
Ah my bad...
I'll add a DB update script asap

**Pull request merged**
