### PR TITLE
No sounds bug

### PR DESCRIPTION
**Pull request by Topvennie**
Fixes the sound bug #375 

Haven't actually tested it but it should work.

### CODE REVIEW

**Comment by Topvennie** [comment]
Added a wr difference message after "{1} {yellow}{2} {default}beat the map record!"

**Review by dPexxIAM — APPROVED** [review]
ty!

**Comment by tslashd** [comment]
Does this fix the issue with styled map and bonus SR's not being forwarded correctly? @Topvennie

**Comment by dPexxIAM** [comment]
> Does this fix the issue with styled map and bonus SR's not being forwarded correctly? @Topvennie

No. This was never mentioned anywhere on Git. Make another issue.

**Comment by tslashd** [comment]
> > Does this fix the issue with styled map and bonus SR's not being forwarded correctly? @Topvennie
> 
> No. This was never mentioned anywhere on Git. Make another issue.
ty #382

**Pull request merged**
