### PR TITLE
Added Surftimer-Web-Stats into Extensions

### PR DESCRIPTION
**Pull request by KristianP26**

### CODE REVIEW

**Comment by Bara** [comment]
I would move it to Recommended, Extensions are sourcemod things

**Comment by KristianP26** [comment]
done

**Review by Bara — APPROVED** [review]
I see no problems here, Interface looks good and posted some suggestions for future updates on discord.

**Review by LubricantJam — APPROVED** [review]
All looks well, simple change approved.

**Comment by olokos** [comment]
Awesome work! 👍

**Pull request merged**
