### PR TITLE
another fix for Trigger OnEndTouch issue that keeping velocity when using teleport command

### PR DESCRIPTION
**Pull request by Ciallo-Ani**
<del>not 100% fix if someone set their startzone inside a map trigger OnEndTouch boost zone</del> 
thanks dpexx's idea

### CODE REVIEW

**Review by dPexxIAM — COMMENTED** [review]
it seems like this fix isn't doing anything different that what i PR'd, other that changing variable names and calling them slightly different. unless i'm wrong..

Any reason why you set g_bTeleByCommand[client] = true; in each commands function rather than just calling it inside TeleportClient?

**Comment by Ciallo-Ani** [comment]
just imaging ur standing on a big ground that full of endtouch trigger, and u cannot back to the start zone by command directly

i am not sure whether `TeleportClient` function will be only used command or not in the future

**Comment by dPexxIAM** [comment]
Did you test your code? When I implemented it, it seemed to just nuke the output of the trigger entirely.




> just imaging ur standing on a big ground that full of endtouch trigger, and u cannot back to the start zone by command directly
> 
> i am not sure whether `TeleportClient` function will be only used by command or not in the future

This shouldn't cause that many issues but i can agree it isn't ideal.

You should use TeleportClient instead.

**Review by dPexxIAM — APPROVED** [review]
looks good, thanks!!

**Pull request merged**
