### PR TITLE
Make discord as optional feature

### PR DESCRIPTION
**Pull request by Bara**

### CODE REVIEW

**Comment by Kyli3Boi** [comment]
image

**Comment by Kyli3Boi** [comment]
Sorry for posting this twice but i thought it was me making the error but i got everything running with the latest dev and then used the optional discord branch and replaced the scripting and translations folders from dev with optional discord. Compiled SurfTimer and SurfTimer-Discord and then i get this error again
image

**Comment by sneak-it** [comment]
This PR fixes it: https://github.com/Deathknife/sourcemod-discord/pull/24

**Comment by Kyli3Boi** [comment]
Thanks sneak-it that does solve that issue. 

Just a question SurfTimer-Discord still requires Discord-API in order to function. Is that how its supposed to be?

**Comment by sneak-it** [comment]
> Thanks sneak-it that does solve that issue.
> 
> Just a question SurfTimer-Discord still requires Discord-API in order to function. Is that how its supposed to be?

Ideally Discord-API is only a compile-time requirement, not a requirement to run the timer. After updating your Discord API include files with the ones from the above linked PR and recompiling, do you still encounter issues running the timer without Discord API?

**Comment by Kyli3Boi** [comment]
Yes that is correct.
image

**Comment by sneak-it** [comment]
> Yes that is correct. [EDIT] what i mean is that SurfTimer loads fine but the Surftimer-Discord does not load unless Discord API.smx is loaded also.
> image

Seems reasonable and fairly intentional, you cannot run the Discord module without Discord-API.

**Comment by Kyli3Boi** [comment]
I see thanks for clearing that up just wanted to make sure.

**Comment by Bara** [comment]
That was the reason for "SurfTimer_discord.smx", without the PR by @sneak-it you can't use Discord-API as optional plugin. By creating "SurfTimer_discord.smx" you can use SurfTimer without Discord-API, so it's more an workaround.

**Comment by Kyli3Boi** [comment]
Understood however i still was not able to get SurfTimer_discord.smx to work without using the above PR from sneak-it

**Comment by Bara** [comment]
Try it with this commit

**Comment by Kyli3Boi** [comment]
Yep that seems to work Bara, SurfTimer-Discord is now loading without having Discord API loaded also

**Comment by Kyli3Boi** [comment]
Just to clarify if someone else reads over this. 

SurfTimer-Discord will load without errors, without having Discord API also loaded however it will not work without Discord API being loaded as returns Native not bound errors

**Comment by Bara** [comment]
I'll rework this today or in the next days. Deathknife merged @sneak-it PR and we can do this without SurfTimer_discord now.

**Pull request closed without merging**
