### PR TITLE
Change of some column data types

### PR DESCRIPTION
**Pull request by Bara**
This needs manually executed.

### CODE REVIEW

**Review by dPexxIAM — APPROVED** [review]

**Comment by dPexxIAM** [comment]
@LubricantJam unsure if you've seen the recent discussions on discord about this. should take a look

**Comment by LubricantJam** [comment]
> @LubricantJam unsure if you've seen the recent discussions on discord about this. should take a look

I am running them already, seems to be working perfectly. I'm alright with this to be approved.

**Review by LubricantJam — APPROVED** [review]

**Comment by Bara** [comment]
Fine, we should add an LogMessage when we add new columns/tables as information. For now it should be enough, maybe add this into the wiki @Kyli3Boi

**Comment by LubricantJam** [comment]
@Bara There is a spelling mistake for `reachangelog` to `readchangelog`.

**Pull request merged**
