### PR TITLE
Give weapon with skin

### PR DESCRIPTION
**Pull request by Kxnrl**

### CODE REVIEW

**Comment by Ciallo-Ani** [comment]
猫佬也有想不开的一天

**Comment by Kxnrl** [comment]
> 猫佬也有想不开的一天

??

**Comment by dPexxIAM** [comment]
Just so I'm following, this makes the client's skins show up when on the server, right? @Ciallo-Ani

**Comment by Ciallo-Ani** [comment]
> Just so I'm following, this makes the client's skins show up when on the server, right? @Ciallo-Ani

yep

**Review by dPexxIAM — APPROVED** [review]
looks good, thanks!

**Pull request merged**
