### PR TITLE
Fix for issue 236

### PR DESCRIPTION
**Pull request by Bara**

### CODE REVIEW

**Review by Kyli3Boi — APPROVED** [review]
Tested throughout the fixing process with Bara and can confirm working.

This was also improved by Bara as it now follows the speed mode you are using. EG. When comparing, if you are using xy speed the comparison will be in xy and if using xyz the comparison will be in xyz.

**Comment by LubricantJam** [comment]
Not sure how I approve from mobile but I'm trying to do so, if someone beats me to it feel free.

**Review by LubricantJam — APPROVED** [review]

**Review by LubricantJam — APPROVED** [review]
Good to go!

**Comment by dPexxIAM** [comment]
> Tested throughout the fixing process with Bara and can confirm working.
> 
> This was also improved by Bara as it now follows the speed mode you are using. EG. When comparing, if you are using xy speed the comparison will be in xy and if using xyz the comparison will be in xyz.

Nice change, however, it's pointless to compare start zones in XY units. Start zones should always compare using XYZ, and stage zones should do the same unless the prespeed is set to 0 (in staged-linears)

**Review by dPexxIAM — APPROVED** [review]
LGTM

**Comment by Kyli3Boi** [comment]
> > Tested throughout the fixing process with Bara and can confirm working.
> > This was also improved by Bara as it now follows the speed mode you are using. EG. When comparing, if you are using xy speed the comparison will be in xy and if using xyz the comparison will be in xyz.
> 
> Nice change, however, it's pointless to compare start zones in XY units. Start zones should always compare using XYZ, and stage zones should do the same unless the prespeed is set to 0 (in staged-linears)

At least having it this way the player is able to decide what they want. I personally am a much bigger fan of speed in xy (just because this is how i was introduced to surf) and i know many many players that prefer just seeing xy speed also.

**Comment by dPexxIAM** [comment]
> > > Tested throughout the fixing process with Bara and can confirm working.
> > > This was also improved by Bara as it now follows the speed mode you are using. EG. When comparing, if you are using xy speed the comparison will be in xy and if using xyz the comparison will be in xyz.
> > 
> > 
> > Nice change, however, it's pointless to compare start zones in XY units. Start zones should always compare using XYZ, and stage zones should do the same unless the prespeed is set to 0 (in staged-linears)
> 
> At least having it this way the player is able to decide what they want. I personally am a much bigger fan of speed in xy (just because this is how i was introduced to surf) and i know many many players that prefer just seeing xy speed also.

You can prestrafe really badly and still achieve max XY units. This will be misleading to new players, and counter-productive to those trying to improve.

**Pull request merged**
